@echo off
echo Preserving Dinosaurs...
xcopy /Y "%localappdata%\UNDERTALE" "%CD%\Dinosaur\"
echo Loading Savestate...
rmdir /S /Q "%localappdata%\UNDERTALE"
xcopy /Y "%CD%\Undertale Save" "%localappdata%\UNDERTALE\" /I
echo Starting Undertale...
Undertale\UNDERTALE.exe
echo Updating Savestate...
xcopy /Y "%localappdata%\UNDERTALE" "%CD%\Undertale Save\" /I
rmdir /S /Q "%localappdata%\UNDERTALE"
echo Restoring Dinosaurs...
xcopy /Y "%CD%\Dinosaur" "%localappdata%\UNDERTALE\"
rmdir /S /Q "%CD%\Dinosaur"
pause